### ISSUE TITLE
Account Charts - Transactions - Today TOP Transactions

### ISSUE THREAD

**Issue by bro-n-bro-2** [bro-n-bro/bro_monitor#17]
swagger-ui/#/statistics/get_statistics_popular_transactions

**Comment by bro-n-bro-2** [comment]
Update description from Today to Month

**Comment by bro-n-bro-2** [comment]
When you navigate in the right table of donut graph, make sectors highlighted.

**Comment by bro-n-bro-2** [comment]
If possible, merge transaction messages less than 10k into one and name it Other.

**Comment by bro-n-bro-0** [comment]
@prevetal @irahunt 
<img width="1191" alt="image" src="https://github.com/bro-n-bro/bro_monitor/assets/89854952/e5402281-c19a-4bc1-a341-781b90fb5804">
