### ISSUE TITLE
Account Graphs - Governance - The number of those who received unique addresses in the voting

### ISSUE THREAD

**Issue by bro-n-bro-2** [bro-n-bro/bro_monitor#20]
Please, update Transaction to Governance
swagger-ui/#/gov/get_gov_votes

**Comment by bro-n-bro-0** [comment]
<img width="1616" alt="image" src="https://github.com/bro-n-bro/bro_monitor/assets/89854952/726d6ab0-c498-4aa0-9b57-edc7841e33da">

replace the numbers to not confuse a user

**Comment by bro-n-bro-2** [comment]
@bro-n-bro-0 @iljagrabar14 please, sort by desc swagger-ui/#/gov/get_gov_votes
add total proposals to endpoint.

@irahunt , please add pagination as discussed.

**Comment by bro-n-bro-2** [comment]
#27 for pagination reference

**Comment by iljagrabar14** [comment]
> @bro-n-bro-0 @iljagrabar14 please, sort by desc swagger-ui/#/gov/get_gov_votes add total proposals to endpoint.
> 
> @irahunt , please add pagination as discussed.

done, ready for test

**Comment by bro-n-bro-2** [comment]
Show in open window 20 props or more
