### ISSUE TITLE
Account Graphs - Governance - The number of those who received unique addresses in the voting

### ISSUE THREAD

**Issue by bro-n-bro-2** [bro-n-bro/bro_monitor#27]
![image](https://github.com/bro-n-bro/bro_monitor/assets/89855562/32d7c97d-edcf-4cd6-9914-c44fd1888e8e)
Please, remove time picker.  #20 
please, add page count. 
![image](https://github.com/bro-n-bro/bro_monitor/assets/89855562/5c27a230-f90e-4c75-a5d8-a4df4f5d884d)

**Comment by irahunt** [comment]
<img width="1068" alt="Снимок экрана 2023-11-12 в 00 11 43" src="https://github.com/bro-n-bro/bro_monitor/assets/106156987/b1dcc354-c4ad-40d5-be30-6f40f139fd4a">

hi, [check it](https://www.figma.com/file/qhmlIKVNDNUFfdkOZqhvnR/%F0%9F%91%8A%F0%9F%8F%BB-bro_n_bro-team?type=design&node-id=5385-91511&mode=design&t=J0InBsQvkpOHT894-4)
