### ISSUE TITLE
Create one more staking modal window

### ISSUE THREAD

**Issue by bro-n-bro-2** [bro-n-bro/bro_monitor#30]
![image](https://github.com/bro-n-bro/bro_monitor/assets/89855562/63d9d89d-67fa-4e5b-a20d-bbef5ef92183)

**Comment by irahunt** [comment]
https://www.figma.com/file/qhmlIKVNDNUFfdkOZqhvnR/%F0%9F%91%8A%F0%9F%8F%BB-bro_n_bro-team?type=design&node-id=7763-29204&mode=design&t=ZSuZJ5zDW9pHlCRZ-4

**Comment by bro-n-bro-2** [comment]
To unlock full features stake min of **20** Atom
