### ISSUE TITLE
Move charts to new tabs

### ISSUE THREAD

**Issue by bro-n-bro-2** [bro-n-bro/bro_monitor#31]
![image](https://github.com/bro-n-bro/bro_monitor/assets/89855562/06ab9181-6b4c-4f41-919d-dd265dc356b1)

TRX: - Rich List, Whale Transactions, Month TOP Transactions
GOV: - Unique votes per proposal, Governance Participation

**Comment by irahunt** [comment]
https://www.figma.com/file/qhmlIKVNDNUFfdkOZqhvnR/%F0%9F%91%8A%F0%9F%8F%BB-bro_n_bro-team?type=design&node-id=7807-34312&mode=design&t=7LUSs52NbkaC5lvm-4

**Comment by bro-n-bro-2** [comment]
Fix TRX to TX and add icon.
Thanks

**Comment by irahunt** [comment]
[Done.](https://www.figma.com/file/qhmlIKVNDNUFfdkOZqhvnR/%F0%9F%91%8A%F0%9F%8F%BB-bro_n_bro-team?type=design&node-id=5704-110859&mode=design&t=ZcvyXbJuW0xueNE5-4)

**Comment by bro-n-bro-2** [comment]
@prevetal , please, proceed
