### ISSUE TITLE
Move tooltip under networks during scroll

### ISSUE THREAD

**Issue by bro-n-bro-2** [bro-n-bro/bro_monitor#37]
Move tooltip under networks during scroll. Just an example, don't need to implement on prod as for now.

**Comment by irahunt** [comment]
1 — 
https://www.figma.com/proto/qhmlIKVNDNUFfdkOZqhvnR/%F0%9F%91%8A%F0%9F%8F%BB-bro_n_bro-team?page-id=5039%3A82287&type=design&node-id=7818-32173&viewport=4241%2C-2198%2C0.63&t=HNdGiakAomvBEyre-1&scaling=min-zoom&starting-point-node-id=5403%3A87232&mode=design


2 — https://www.figma.com/proto/qhmlIKVNDNUFfdkOZqhvnR/%F0%9F%91%8A%F0%9F%8F%BB-bro_n_bro-team?page-id=5039%3A82287&type=design&node-id=7818-30001&viewport=2255%2C-595%2C0.21&t=uabaEFZ4xcTNsHHC-1&scaling=min-zoom&starting-point-node-id=5403%3A87232&mode=design

**Comment by irahunt** [comment]
https://www.figma.com/file/qhmlIKVNDNUFfdkOZqhvnR/%F0%9F%91%8A%F0%9F%8F%BB-bro_n_bro-team?type=design&node-id=7889-61722&mode=design&t=sr31e009WpA0jPGF-4
