### ISSUE TITLE
Make watermark more/less visible

### ISSUE THREAD

**Issue by bro-n-bro-2** [bro-n-bro/bro_monitor#39]
https://stats.bronbro.io/network/cosmoshub?tab=4&type=1
https://stats.bronbro.io/network/cosmoshub?tab=3&type=1

**Comment by irahunt** [comment]
https://www.figma.com/file/qhmlIKVNDNUFfdkOZqhvnR/%F0%9F%91%8A%F0%9F%8F%BB-bro_n_bro-team?type=design&node-id=7818-27322&mode=design&t=AGPHWt7zApViju49-4
