### ISSUE TITLE
Design a roll up menu with chains

### ISSUE THREAD

**Issue by bro-n-bro-2** [bro-n-bro/bro_monitor#47]
Design a roll up menu with chains
as reference 
![image](https://github.com/bro-n-bro/bro_monitor/assets/89855562/4a690f06-d385-4d1d-83b5-b8a443e15899)

**Comment by irahunt** [comment]
Done: https://www.figma.com/file/qhmlIKVNDNUFfdkOZqhvnR/%F0%9F%91%8A%F0%9F%8F%BB-bro_n_bro-team?type=design&node-id=7914-99328&mode=design&t=ZcvyXbJuW0xueNE5-4

**Comment by bro-n-bro-2** [comment]
Looks very good!
@prevetal , please, proceed
