### ISSUE TITLE
Add links to other dashboards on stats.bronbro.io

### ISSUE THREAD

**Issue by bro-n-bro-2** [bro-n-bro/bro_monitor#48]
![image](https://github.com/bro-n-bro/bro_monitor/assets/89855562/7fa5973a-615b-4e3e-b8b4-15a58e028b42)

https://monitor.bronbro.io/

@irahunt could you please add all logos to Figma ?

**Comment by irahunt** [comment]
https://www.figma.com/file/qhmlIKVNDNUFfdkOZqhvnR/%F0%9F%91%8A%F0%9F%8F%BB-bro_n_bro-team?type=design&node-id=6115-105908&mode=design&t=ZcvyXbJuW0xueNE5-4

**Comment by bro-n-bro-2** [comment]
Please, add star/pin option.

**Comment by irahunt** [comment]
> Please, add star/pin option.

https://www.figma.com/file/qhmlIKVNDNUFfdkOZqhvnR/%F0%9F%91%8A%F0%9F%8F%BB-bro_n_bro-team?type=design&node-id=6115-105908&mode=design&t=ZcvyXbJuW0xueNE5-4
