### ISSUE TITLE
Create rich list table

### ISSUE THREAD

**Issue by bro-n-bro-2** [bro-n-bro/bro_monitor#50]
Create rich list table
 {
      "address": "cosmos1fl48vsnmsdzcv85q5d2q4z5ajdha8yu34mf0eh",
      "delegated": 0,
      "liquid": 177223800294881,
      "sum": 177223800294881,
      "type": "/cosmos.auth.v1beta1.ModuleAccount",
      "unbonding": 0
    },

**Comment by irahunt** [comment]
https://www.figma.com/file/qhmlIKVNDNUFfdkOZqhvnR/%F0%9F%91%8A%F0%9F%8F%BB-bro_n_bro-team?type=design&node-id=5575-90279&mode=design&t=qSKUhpjhxLBhCL99-4

**Comment by bro-n-bro-2** [comment]
@prevetal , you can proceed further

**Comment by bro-n-bro-2** [comment]
/statistics/get_statistics_rich_list
