### ISSUE TITLE
Add to price Celestia, neutron and agoric colors

### ISSUE THREAD

**Issue by bro-n-bro-2** [bro-n-bro/bro_monitor#55]
https://stats.bronbro.io/prices

**Comment by irahunt** [comment]
https://www.figma.com/file/qhmlIKVNDNUFfdkOZqhvnR/%F0%9F%91%8A%F0%9F%8F%BB-bro_n_bro-team?type=design&node-id=5622-90764&mode=design&t=qSKUhpjhxLBhCL99-4

**Comment by bro-n-bro-2** [comment]
price_feed_api//tokens/?symbol__in=BLD%2CNTRN%2CTIA
