### ISSUE TITLE
Add price panel on main page

### ISSUE THREAD

**Issue by bro-n-bro-2** [bro-n-bro/bro_monitor#61]
![image](https://github.com/bro-n-bro/bro_monitor/assets/89855562/35f92ae2-2feb-4f02-9013-e7c4cb4b8ee0)

**Comment by irahunt** [comment]
https://www.figma.com/file/qhmlIKVNDNUFfdkOZqhvnR/%F0%9F%91%8A%F0%9F%8F%BB-bro_n_bro-team?type=design&node-id=6115-105908&mode=design&t=p1prDEB0aj1KPMeH-4
