### ISSUE TITLE
Change colors

### ISSUE THREAD

**Issue by bro-n-bro-2** [bro-n-bro/bro_monitor#66]
https://stats.bronbro.io/cosmoshub/chart/accounts_statistics

**Comment by bro-n-bro-2** [comment]
Inactive accounts - blue
New accounts - red

**Comment by irahunt** [comment]
<img width="1095" alt="Снимок экрана 2024-01-25 в 09 47 48" src="https://github.com/bro-n-bro/bro_monitor/assets/106156987/13cf97de-2283-43eb-9042-5f9f31fdbb56">
done
