### ISSUE TITLE
Add column "% of total supply"

### ISSUE THREAD

**Issue by bro-n-bro-2** [bro-n-bro/bro_monitor#67]
![image](https://github.com/bro-n-bro/bro_monitor/assets/89855562/18f19dc9-4659-4d06-8165-145dbfdce528)
Please, add new column "% of total supply" as a last column.

**Comment by irahunt** [comment]
https://www.figma.com/file/qhmlIKVNDNUFfdkOZqhvnR/%F0%9F%91%8A%F0%9F%8F%BB-bro_n_bro-team?type=design&node-id=5575-90279&mode=design&t=CpKU7r1KKplornh2-4
