### ISSUE TITLE
Add Dymension to prices and create a link on main page and add to left side

### ISSUE THREAD

**Issue by bro-n-bro-2** [bro-n-bro/bro_monitor#69]
Add Dymension to prices and create a link on main page and add to left side

**Comment by prevetal** [comment]
1. I need url for the "Stake with your bro" button.

2. https://rpc.bronbro.io/bro_data/ - Dymension should be added here

**Comment by bro-n-bro-2** [comment]
@irahunt , add dymension logo to main page and to left scroll bar

**Comment by irahunt** [comment]
@prevetal 
Done
Link — https://www.figma.com/file/qhmlIKVNDNUFfdkOZqhvnR/%F0%9F%91%8A%F0%9F%8F%BB-bro_n_bro-team?type=design&node-id=8259-81874&mode=design&t=7JpgRbBGSAAZ61yy-4
