### ISSUE TITLE
Add Archaway, Band, Injective, Neutron to main page on stats

### ISSUE THREAD

**Issue by bro-n-bro-2** [bro-n-bro/bro_monitor#70]
@irahunt , please, create panels
@prevetal implement after

Links: https://monitor.bronbro.io/d/archway-stats/
https://monitor.bronbro.io/d/band-stats/
https://monitor.bronbro.io/d/injective-stats/
https://monitor.bronbro.io/d/neutron-stats/

**Comment by irahunt** [comment]
@prevetal 
<img width="1679" alt="Снимок экрана 2024-02-17 в 21 51 14" src="https://github.com/bro-n-bro/bro_monitor/assets/106156987/4d86e650-3e07-4cfe-9ded-5aaf80a395a6">
https://www.figma.com/file/qhmlIKVNDNUFfdkOZqhvnR/%F0%9F%91%8A%F0%9F%8F%BB-bro_n_bro-team?type=design&node-id=7911-92312&mode=design&t=nMGb9vO5Opfzj6eJ-4
