### ISSUE TITLE
Saga

### ISSUE THREAD

**Issue by bro-n-bro-2** [bro-n-bro/bro_monitor#74]
Add Saga to https://stats.bronbro.io/prices

**Comment by prevetal** [comment]
what color?

**Comment by bro-n-bro-2** [comment]
@ultracosmoboy , please, add color to Saga

**Comment by ultracosmoboy** [comment]
https://www.figma.com/file/U310X25nqy71k6KIBswsg9/Bro_n_Bro-Team?type=design&node-id=1%3A39696&mode=design&t=d1oTjuKTElyI4Lzt-1
<img width="556" alt="Снимок экрана 2024-05-08 в 00 30 09" src="https://github.com/bro-n-bro/bro_monitor/assets/167297694/536f6049-d67f-4d34-ba8a-e90cf0564d96">
<img width="814" alt="Снимок экрана 2024-05-08 в 00 31 13" src="https://github.com/bro-n-bro/bro_monitor/assets/167297694/42cbeba8-5169-43ea-b5bf-a796ebe96591">
